### ISSUE TITLE
REQUIRED process [sitl-2] has died!

### ISSUE THREAD

**Issue by tangjr2020** [MikeS96/autonomous_landing_uav#15]
When running "roslaunch mavros_off_board mavros_posix_sitl.launch" ,here goes the question:
process[mavros-6]: started with pid [25837]
sh: 0: Can't open /etc/init.d/rc.mc_defaults
ERROR [px4] Startup script returned with return value: 32512
process[image_view-7]: started with pid [25861]
================================================================================REQUIRED process [sitl-2] has died!
process has died [pid 25757, exit code 255, cmd /home/tang/PX4-Autopilot/build/bin/px4 /home/tang/PX4-Autopilot/build/px4_sitl_default/etc -s etc/init.d-posix/rcS __name:=sitl __log:=/home/tang/.ros/log/b0d8d93e-e7f6-11ec-9ccd-899b4f4ecf5b/sitl-2.log].
log file: /home/tang/.ros/log/b0d8d93e-e7f6-11ec-9ccd-899b4f4ecf5b/sitl-2*.log
Initiating shutdown!
================================================================================
[image_view-7] killing on exit
[mavros-6] killing on exit
[gazebo_gui-4] killing on exit
[gazebo-3] killing on exit
[vehicle_spawn_tang_virtual_machine_25731_1574410395322002380-5] killing on exit
[sitl-2] killing on exit
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 148, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 142, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/opt/ros/noetic/lib/python3/dist-packages/gazebo_msgs/__init__.cpython-38-x86_64-linux-gnu.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/gazebo_ros/spawn_model", line 29, in <module>
    from gazebo_ros import gazebo_interface
  File "/opt/ros/noetic/lib/python3/dist-packages/gazebo_ros/gazebo_interface.py", line 9, in <module>
    from gazebo_msgs.msg import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1407, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1379, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1525, in find_spec
  File "<frozen importlib._bootstrap_external>", line 156, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 148, in _path_is_mode_type
KeyboardInterrupt
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

And I just try many methods in previous issue, however , I cannot know how to slove it

**Comment by tangjr2020** [comment]
It shows a  "KeyboardInterrupt" ,but I exectly don't do that!

**Comment by MikeS96** [comment]
Hi @tangjr2020 

Based on the error logs `FileNotFoundError: [Errno 2] No such file or directory: '/opt/ros/noetic/lib/python3/dist-packages/gazebo_msgs/init.cpython-38-x86_64-linux-gnu.so'` maybe trying `sudo apt-get install ros-noetic-gazebo-*` would solve the dependency issue. 

Miguel.
