### ISSUE TITLE
Error while running Teleop

### ISSUE THREAD

**Issue by dsriaditya999** [MikeS96/autonomous_landing_uav#24]
Hello,

Thank you for sharing such a good resource. I had followed all the steps for installation but I am getting an error when I run the following line:

```
rosrun mavros_off_board teleop_node_pos
```

It says that it could not find the executable teleop_node_pos. I noticed that there is no mention of this in the CMakeLists.txt. Can that be a reason? 

It would be great if you look into this. Thank you!

**Comment by Comor543** [comment]
Hello,
Same problem here.
I even did what @MikeS96 answered in Q3 in https://github.com/MikeS96/autonomous_landing_uav/issues/9#issuecomment-948625474 and in https://github.com/MikeS96/autonomous_landing_uav/issues/9#issuecomment-949650526

as @MikeS96 said in https://github.com/MikeS96/autonomous_landing_uav/issues/9#issuecomment-949650526, if I run
```
rosrun mavros_off_board teleop_node_pos.py
```
I get error below
```
Traceback (most recent call last):
  File "/home/user/Autonomos_landing_ws/devel/lib/mavros_off_board/teleop_node_pos.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/user/Autonomos_landing_ws/src/autonomous_landing_uav/mavros_off_board/scripts/teleop_node_pos.py", line 5, in <module>
    import roslib; roslib.load_manifest('teleop_twist_keyboard')
  File "/opt/ros/noetic/lib/python3/dist-packages/roslib/launcher.py", line 64, in load_manifest
    sys.path = _generate_python_path(package_name, _rospack) + sys.path
  File "/opt/ros/noetic/lib/python3/dist-packages/roslib/launcher.py", line 97, in _generate_python_path
    m = rospack.get_manifest(pkg)
  File "/usr/lib/python3/dist-packages/rospkg/rospack.py", line 171, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/python3/dist-packages/rospkg/rospack.py", line 215, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)
  File "/usr/lib/python3/dist-packages/rospkg/rospack.py", line 207, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: teleop_twist_keyboard
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/user/Autonomos_landing_ws/src
ROS path [2]=/opt/ros/noetic/share
ROS path [3]=/home/user/PX4-Autopilot
ROS path [4]=/home/user/PX4-Autopilot/Tools/sitl_gazebo
```

**Comment by MikeS96** [comment]
Hi @dsriaditya999, please see https://github.com/MikeS96/autonomous_landing_uav/issues/9#issuecomment-948625474.

@Comor543 it seems like it is having problems finding the `teleop_twist_keyboard` package, have you tried
`sudo apt-get install ros-noetic-teleop-twist-keyboard`?

**Comment by Comor543** [comment]
Hello @MikeS96 thank you for considering our problems.
I install ```ros-noetic-teleop-twist-keyboard``` by ```sudo apt-get install ros-noetic-teleop-twist-keyboard``` as you said and works for me. However, before I was informed you answered my question I just commented ```roslib.load_manifest('teleop_twist_keyboard')``` in file ```teleop_node_pos.py``` then run ```catkin_make``` and it worked too.
```
import roslib; # roslib.load_manifest('teleop_twist_keyboard')
```
This way it works for me, but IDK why :D.
Just wanted to inform you.
